databases:
  - name: collectionmanagementapp
    databaseName: collectionmanagementapp_ekxt
    user: collectionmanagementapp_ekxt_user

services:
  - type: web
    name: collectionmanagementapp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: collectionmanagementapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false